# Generated by Django 4.1.2 on 2022-11-03 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_player', models.IntegerField(verbose_name='Minimum # Players')),
                ('max_player', models.IntegerField(blank=True, null=True, verbose_name='Maximum # Players')),
                ('avg_game_play', models.IntegerField()),
                ('difficulty_rating', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('min_age', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True, max_length=250, verbose_name='Private notes (e.g., strategy, etc.)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(verbose_name='Meeting Date')),
                ('location', models.CharField(max_length=100)),
                ('min_ppl', models.IntegerField(verbose_name='Minimum # of players')),
                ('max_ppl', models.IntegerField(verbose_name='Maximum # of players')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(related_name='user_playing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.game')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_photo', to='main_app.meeting')),
            ],
        ),
    ]
