# Generated by Django 4.1.2 on 2022-10-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='difficulty_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_player',
            field=models.IntegerField(null=True),
        ),
    ]
