# Generated by Django 4.1.2 on 2022-10-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.game'),
        ),
    ]
