# Generated by Django 4.1.2 on 2022-10-31 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_alter_meeting_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='players',
            field=models.ManyToManyField(null=True, related_name='user_playing', to=settings.AUTH_USER_MODEL),
        ),
    ]
