# Generated by Django 4.1.2 on 2022-10-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_meeting_organizer_alter_meeting_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='max_ppl',
            field=models.IntegerField(verbose_name='Maximum # of players'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='min_ppl',
            field=models.IntegerField(verbose_name='Minimum # of players'),
        ),
    ]
