# Generated by Django 4.1.2 on 2022-10-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_meeting_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='max_player',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum # Players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_player',
            field=models.IntegerField(verbose_name='Minimum # Players'),
        ),
    ]
